### PR TITLE
Fix scaling up image with RoundingParams #2293

### PR DESCRIPTION
**Pull request by otopba**
## Motivation

This is fix for issue #2293

## Test Plan

Try to reproduce the case from issue # 2293. You should see two identical pictures.

### CODE REVIEW

**Comment by erikandre** [comment]
Hi @otopba ! 

Thank you for submitting the this pull request.

**Comment by otopba** [comment]
Hey, @erikandre
Thank you for this awesome library! =)

**Comment by otopba** [comment]
@erikandre check new commit please

**Comment by CaptainHuangsh** [comment]
the problem is still exit #2.4.0

**Comment by entropy2012** [comment]
the problem is still exit v2.6.0 on Android 9

**Pull request closed without merging**
