### PR TITLE
inline proguard rules

### PR DESCRIPTION
**Pull request by gengjiawen**
## Motivation (required)

Android library should maintain their own proguard rules like butterknife, so library user should manually copy and paste proguard rules everytime the rules updated.

## Test Plan (required)

Test current sample app works as expect.

### CODE REVIEW

**Comment by gengjiawen** [comment]
@lambdapioneer Has this pr got merged, do I need to close this ?

**Comment by lambdapioneer** [comment]
It's not merged yet :) I've imported it to our internal system to verify it and get comments from my colleagues.

Once it is merged, this pull-request will close automatically

**Comment by lambdapioneer** [comment]
Hi @gengjiawen this looks good :)

However, can you remove the update of the documentation for now? We'd want to wait with it until we made the new release.

**Comment by gengjiawen** [comment]
@lambdapioneer done.

**Comment by gengjiawen** [comment]
@lambdapioneer Since the new version has been released, I think we need to update the docs.

**Pull request closed without merging**
