### PR TITLE
Add support for dynamically changing backgrounds and overlays

### PR DESCRIPTION
**Pull request by plamenko**
Summary: Allows backgrounds and overlays to be changed dynamically. Note, DraweeHierarchy space for backgrounds and overlays need to be preallocated in advance in order to be changed.

Test Plan: Verified in the sample app that:
    * setting background dynamically works
    * setting overlay dynamically works
    * setting both a background and an overlay dynamically works
    * attempting to set a backgroudn or an overlay without preallocating throws

### CODE REVIEW

**Comment by plamenko** [comment]
screen shot 2016-05-19 at 20 26 51

**Comment by kirwan** [comment]
Thanks for the PR @plamenko. It looks great.

@facebook-github-bot-0 import

**Comment by kirwan** [comment]
This looks good to me. I'm importing it now so we can merge it.

**Comment by kirwan** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1091733137553739/int_phab) to review.

**Pull request closed without merging**
