### PR TITLE
Update repo link in footer

### PR DESCRIPTION
**Pull request by andrewimm**
"redex" => "fresco" :)

### CODE REVIEW

**Comment by andrewimm** [comment]
Also, I love that I was able to do this without leaving github.com

**Comment by kirwan** [comment]
Thanks very much. The new website just went live yesterday and we hadn't noticed that.

**Comment by matthewjohnston4** [comment]
Oh, actually, I'll suggest an improvement here. Because `ghrepo` is defined in [_config.yml](https://github.com/facebook/fresco/blob/gh-pages/_config.yml#L13) it becomes available to use in templates like this footer as {{ site.ghrepo }}, so you should be able to change that to:

```
 <a class="footerLink" href="https://github.com/{{ site.ghrepo }}" target="_blank">Contribute to this project on GitHub</a>
```

**Comment by kirwan** [comment]
OK, I've just merged the PR so I'll change that separately.

**Pull request merged**
