### PR TITLE
Fix GIF not shows static image without animated-gif dependency

### PR DESCRIPTION
**Pull request by s1rius**

### CODE REVIEW

**Comment by parane** [comment]
so  setAutoPlayAnimations=false , can we show preview static image without decode the whole frame ?

**Comment by oprisnik** [comment]
Can you give a more detailed description what this diff solves and how it worked before / after (Screenshots or a video would help as well)?

**Comment by s1rius** [comment]
@oprisnik This issue is could be reproduced like this:
1.Change the dependencies of the demo app which is one of Fresco's samples like this
```
dependencies {
    provided "com.android.support:support-annotations:${SUPPORT_LIB_VERSION}"
    compile 'com.facebook.fresco:fresco:0.11.0'
//    internalCompile project(':drawee-backends:drawee-pipeline')
//    internalCompile project(':static-webp')
//    internalCompile project(':animated-gif')
//    internalCompile project(':animated-webp')
//
//    // To get the core Fresco library only without animations or webp support
//    mavenBasicCompile 'com.facebook.fresco:fresco:0.11.0'
//
//    // To get the core Fresco library with webp support
//    mavenWithWebpCompile 'com.facebook.fresco:fresco:0.11.0'
//    mavenWithWebpCompile 'com.facebook.fresco:webpsupport:0.11.0'
//
//    // To get the core Fresco library with webp support, including animated webp
//    mavenWithAnimatedWebpCompile 'com.facebook.fresco:fresco:0.11.0'
//    mavenWithAnimatedWebpCompile 'com.facebook.fresco:animated-webp:0.11.0'
//    mavenWithAnimatedWebpCompile 'com.facebook.fresco:webpsupport:0.11.0'
//
//    // To get the core Fresco library with animated gif support
//    mavenWithAnimatedGifCompile 'com.facebook.fresco:fresco:0.11.0'
//    mavenWithAnimatedGifCompile 'com.facebook.fresco:animated-gif:0.11.0'
//
//    // To get the core Fresco library with webp, animated webp and animated gif support
//    mavenWithAllAnimationsCompile 'com.facebook.fresco:fresco:0.11.0'
//    mavenWithAllAnimationsCompile 'com.facebook.fresco:animated-gif:0.11.0'
//    mavenWithAllAnimationsCompile 'com.facebook.fresco:animated-webp:0.11.0'
//    mavenWithAllAnimationsCompile 'com.facebook.fresco:webpsupport:0.11.0'
}
```
2.Run the demo app, you will see the screenshot like this
719f1ec4-d0b0-4fa4-b2ff-e66ae29b31bc
and get this error message:
```
W/unknown:RequestLoggingListener: time 451743358: onRequestFailure: {requestId: 2, elapsedTime: 233 ms, throwable: java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.imagepipeline.image.CloseableImage com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(com.facebook.imagepipeline.image.EncodedImage, com.facebook.imagepipeline.common.ImageDecodeOptions, android.graphics.Bitmap$Config)' on a null object reference}
```
It's not we want. After patched this PR and roll back the demo's dependencies. The GIF images show correctly.
4794347d-4bea-4b06-bfd7-ef478fb7a226
Unfortunately, WebP image show a error placeholder. I got this:
```
onRequestFailure: {requestId: 7, elapsedTime: 216 ms, throwable: java.lang.IllegalArgumentException: Problem decoding into existing bitmap}
```
And I have no idea to fix it right now.

**Comment by aagnes** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1770383696538219/int_phab) to review.

**Pull request closed without merging**
