### PR TITLE
Enhancement the HttpUrlConnectionNetworkFetcher

### PR DESCRIPTION
**Pull request by helengray**
Enhancement the HttpUrlConnectionNetworkFetcher,when extend the HttpUrlConnectionNetworkFetcher,can override the methond to set the connection property

### CODE REVIEW

**Comment by a631855639** [comment]
I do

**Comment by plamenko** [comment]
Other than the imports being reordered, I don't see any other changes. What am I missing?

**Comment by tyronen** [comment]
It looks like, although GitHub doesn't realize you need a rebase, you do. Your changes are overwritten by code from master.

**Comment by kirwan** [comment]
As the others have said, there doesn't appear to be an actual change here and this has been sitting here for a while.

I'm going to close the PR but you can create a new one if there's something you want to change.

**Pull request closed without merging**
