### PR TITLE
64-bit ARM and x86_64 architecture support (NB: not yet fully tested!)

### PR DESCRIPTION
**Pull request by orospakr**
Needed for the recently released Galaxy S6, among a few other models.

The crash you'd see would be something like:

    E/AndroidRuntime(5325): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.joistapp.android.joist.alpha-1/base.apk"],nativeLibraryDirectories=[/data/app/com.joistapp.android.joist.alpha-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"

* Added the x86_64 and arm64-v8a architectures.
* Fixed pointer-length disagreement cast build failures in gifimage and webp.

I followed the guidance given at http://developer.android.com/training/articles/perf-jni.html.

Unfortunately, I lack a 64-bit ARM device, and the x86_64 emulator is not cooperating with me at the moment, so the best I've done is test for cursory regression in the context of my own app on a 32-bit device (which, I'll note, does not use either GIF or WebP).

### CODE REVIEW

**Comment by orospakr** [comment]
My CTO is looking at the CLA.

**Comment by orospakr** [comment]
Yep, just confirmed that this gets the core functionality of Fresco working on 64-bit phones.  WebP and GIF remain untested, however.

**Comment by orospakr** [comment]
CLA is signed.

**Comment by orospakr** [comment]
Will address the code review shortly!

**Comment by plamenko** [comment]
@orospakr thanks!

**Comment by xialin** [comment]
any progress on this?

**Comment by michalgr** [comment]
We are merging https://github.com/facebook/fresco/pull/176

**Pull request closed without merging**
