### PR TITLE
[bugfix]closeableObject could be closed unsafely in MultiplexProducer.Multiplexer#onNextResult

### PR DESCRIPTION
**Pull request by huangjunkun**
Fix:closeableObject could be closed unsafely in MultiplexProducer.Multiplexer#onNextResult

> Issue: https://github.com/facebook/fresco/issues/1453

### CODE REVIEW

**Comment by huangjunkun** [comment]
Cordially invite @marcosmejia  @lambdapioneer  @kirwan     code review.
Thanks.

**Comment by kirwan** [comment]
Thanks for this @huangjunkun - the change looks good.

Some tests are broken though, as shown by CircleCI. Can you please fix the tests?

**Comment by facebook-github-bot-4** [comment]
@huangjunkun updated the pull request - [view changes](https://github.com/facebook/fresco/pull/1454/files/bf86b77a203cb1694dd0637c408ac9562c4acce1..22bd4a2842a0a8ba66013112381b307ff8da5aae)

**Comment by kirwan** [comment]
Thanks @huangjunkun. This looks great.

@facebook-github-bot import

**Comment by huangjunkun** [comment]
@kirwan  With pleasure.

**Comment by kirwan** [comment]
Yeah, I'll take a look at #1317.

**Comment by kirwan** [comment]
@huangjunkun: After merging this PR, we've seen a number of instances of bitmaps being cleaned up by finalizers due to the `CloseableReference`s not being cleaned up. I think I'm going to have to revert this for now and then we can test the change further.

**Comment by huangjunkun** [comment]
@kirwan   Oh, yeah, and I have found the reason of this problem.

> 
com.facebook.imagepipeline.datasource.CloseableProducerToDataSourceAdapter#onNewResultImpl
 ```
 @Override
  protected void onNewResultImpl(CloseableReference<T> result, boolean isLast) {
    super.onNewResultImpl(CloseableReference.cloneOrNull(result), isLast);
  }
```
Here CloseableReference.cloneOrNull is no need.

**Comment by huangjunkun** [comment]
https://github.com/huangjunkun/fresco/commit/de8b95351d1e1982ebc794c5254d3d5cf685ae4c

**Pull request closed without merging**
