### PR TITLE
Svg

### PR DESCRIPTION
**Pull request by Roma-Lis**
I'd like to add svg rendering functionality to fresco.
I believe it should be useful because of issues ([#329](https://github.com/facebook/fresco/issues/329), [#1000](https://github.com/facebook/fresco/issues/1008), [#1176](https://github.com/facebook/fresco/issues/1176)).
The svg renderer implementation taken from [androidsvg project](http://bigbadaboom.github.io/androidsvg)

### CODE REVIEW

**Comment by oprisnik** [comment]
Thanks for the PR @Roma-Lis!
We're looking into adding custom decoders for Fresco so that you can simply plug in your own decoders, like this one for SVG.
The format shouldn't be too different from the current implementation, so it should be pretty easy to adapt your code once this is ready.

We'll keep you updated!

**Comment by Roma-Lis** [comment]
@oprisnik , thanks. Actual architecture don't support it, but it will be nice to know about view dimensions inside any vector images decoder to avoid redundant rendering.

**Comment by oprisnik** [comment]
Yeah, we are working on making pluggable decoders. We don't know the view dimensions before, but we can enforce that resize options have to be set for the `ImageRequest`.

**Comment by Roma-Lis** [comment]
@oprisnik sure, if it is not a problem to have third-party libraries added via Gradle dependencies in your project.

**Comment by kirwan** [comment]
We now have custom decoders and will be adding a sample very soon for using SVG within Fresco.

I'm closing this pull request but please take a look later in the week.

**Comment by oprisnik** [comment]
A very simple example for SVG support (using the same library as you've used in this PR) can be found here: https://github.com/facebook/fresco/tree/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/svg 

I didn't check if the functionality is exactly the same as in your `SvgDecoder`, but you can just modify the custom decoder to achieve whatever you want.

Thanks for your time!

**Pull request closed without merging**
