### PR TITLE
Switch to Libwebp 0.5.1

### PR DESCRIPTION
**Pull request by eldk**
Hello,

Switch to libwebp 0.5.1

Some libwebp files have moved and some others have been sliced since libwebp 0.5.0

The switch has been tested on device with no webp support and which need static-webp module.

Eric

### CODE REVIEW

**Comment by kirwan** [comment]
Thanks very much Eric. This has reminded me that your previous PR has slipped through the cracks again. Sorry for that. I'll start by importing than then ask you to rebase this one so that this PR is clean of those changes.

**Comment by eldk** [comment]
Ok @kirwan 
Thanks

**Comment by facebook-github-bot-5** [comment]
@eldk updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@eldk updated the pull request.

**Comment by facebook-github-bot-5** [comment]
@eldk updated the pull request.

**Pull request closed without merging**
