### PR TITLE
Fix bug: A IllegalArgumentException caused by file length 0 (get filelength failed!)

### PR DESCRIPTION
**Pull request by huangjunkun**
Fix bug: A IllegalArgumentException caused by file length 0 (get filelength failed!)
https://github.com/facebook/fresco/issues/1315

### CODE REVIEW

**Comment by oprisnik** [comment]
Thank you very much @huangjunkun!

@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1167135026651059/int_phab) to review.

**Comment by huangjunkun** [comment]
Why it warn that Your tests failed on CircleCI.

**Comment by oprisnik** [comment]
It seems that you didn't update your forked repo for quite a long time. Hence, the old version doesn't compile on CircleCI because the Android Build Tools version is too old.

**Pull request closed without merging**
