### PR TITLE
Gradle: Removed nineoldandroids from animated-gif

### PR DESCRIPTION
**Pull request by PiotrWpl**
The same reason as https://github.com/facebook/fresco/commit/362573b00360af2ba99d0b840ca1fb64d1dda619

### CODE REVIEW

**Comment by oprisnik** [comment]
Thank you very much! Once you sign the CLA, I'm going to import this :)

**Comment by PiotrWpl** [comment]
@obishop 
I already signed CLA, just after pull request.

BTW, there is the same change to do with animated-webp ;) Should I make one more pull request, or maybe You will do that?

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/158682157881940/int_phab) to review.

**Pull request closed without merging**
