### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by valentinstoychev**
Add NativeScript to the list of libraries that use Fresco!

### CODE REVIEW

**Comment by michalgr** [comment]
Glad to see such a cool project uses Fresco.

**Comment by valentinstoychev** [comment]
@michalgr Done. Thank you!

**Comment by tyronen** [comment]
This looks good but we need you to sign the CLA as indicated above before we can merge it.

**Comment by massimocarli** [comment]
@valentinstoychev Please sign the CLA here https://code.facebook.com/cla . 
We need this in order to add your project. 
Thanks

**Pull request closed without merging**
