### PR TITLE
Update sdk versions

### PR DESCRIPTION
**Pull request by jlelse**

### CODE REVIEW

**Comment by jlelse** [comment]
I accepted now

**Comment by tyronen** [comment]
Thanks for this change! Sorry for the delay in getting back to you.

Unfortunately this didn't quite work as is. Can you rebase it? 

Also, rather than repeating the versions in each gradle file, could you put them in the gradle.properties file instead?

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment]
Added in modified form.

**Pull request closed without merging**
