### PR TITLE
fix loading local file fail with special character

### PR DESCRIPTION
**Pull request by sailaway**
fix loading local file fail with special character such as "file:///storage/sdcard/QQ??20168898.jpg"

### CODE REVIEW

**Comment by tyronen** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1076006885796752/int_phab) to review.

**Comment by tyronen** [comment]
Hi - we appreciate this contribution, but would feel a lot safer accepting it if there was a unit test :)

**Comment by kirwan** [comment]
I'm going to import this in the spirit of cleaning up and will add a test.

**Pull request closed without merging**
