### PR TITLE
Issue 1940: Fix animated images not playing in SimpleDraweeSpanTextView

### PR DESCRIPTION
**Pull request by Kazemir**
## Motivation (required)

The pull request solves [issue#1940](https://github.com/facebook/fresco/issues/1940). Also it's fix that unscheduleDrawable() calls itself recursively (if it was ever called).

## Test Plan (required)

- Run tests.
- Ensure that DraweeSpan in Showcase app works properly (fist span is still, second is animating).

### CODE REVIEW

**Comment by Kazemir** [comment]
> All checks have failed
Hm, failed tests are in :fbcore module. But I'm only change code in :drawee-span module. Is that some CI trouble?

**Comment by oprisnik** [comment]
Thanks for the pull request! I'll take a look when I have some time.

The CI failure looks unrelated, I'll check that as well.

**Comment by oprisnik** [comment]
Thanks, your change will be included in the next release.

**Comment by Kazemir** [comment]
Thank you for merging :)

**Pull request closed without merging**
