### PR TITLE
updated list with ShareTheMeal app reference in "Who uses Fresco?"

### PR DESCRIPTION
**Pull request by mrsasha**

### CODE REVIEW

**Comment by balazsbalazs** [comment]
Wooohooo! Thx for using Fresco ;)
Amazing and meaningful app! Well done.

I'd love to hear your experiences with Fresco.

**Comment by mrsasha** [comment]
Hey @balazsbalazs, well the experience was pretty uneventful. It's not the first time I've been using Fresco (I used it for 2 other projects but cannot talk about them because NDA) - I've used it to replace Universal Image Loader. UIL worked great but I switched to Fresco because of the memory management and because of the round views, and in general the pipeline is more flexible. Kudos for the good work! :)

PS. Since we did the global launch 2 weeks ago, I noticed some crashes but still didn't have the time to go through them and see if they're reported or not. I hope to do that this week.

**Comment by sleeperabc** [comment]
i'm tring to learn Fresco，it's to hard for me.
but thx.

**Comment by balazsbalazs** [comment]
@mrsasha: good to hear :) Let us know if we can help with anything.

**Comment by balazsbalazs** [comment]
@sleeperabc : ping me on balazs.balazs80@gmail.com with things you find challenging to learn/understand. Maybe we can improve the documentation/examples.

**Pull request merged**
